language: php

php:
    - 5.5

notifications:
    email: false

before_script:
    - phpize
    - ./configure --enable-xdebug
    - make

script:
    - php -f ./travis/copy-binary.php
    - make test | tee test-output.txt && grep 'TEST SUMMARY$' test-output.txt > /dev/null
