language: php

php:
    - 5.5

notifications:
    email: false

before_script:
    - phpize
    - ./configure --enable-xdebug
    - make
    - make install

script:
    - php -f ./travis/copy-binary.php
    - make test
