language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

notifications:
    email: false

before_script:
    - phpize
    - ./configure --enable-xdebug
    - make
    - phpenv config-add ./travis/myconfig.ini

script:
    - php -E "<?php phpinfo(); ?>"
    - make test | tee test-output.txt && grep 'TEST SUMMARY$' test-output.txt > /dev/null
